sudo: required
language: cpp
dist: trusty
compiler: g++

before_install:
  - sudo apt-get -qq update

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - cmake
    - time
    - libjpeg-dev
    - libpng12-dev
    - libfreetype6-dev
    - libmikmod-dev
    - libvorbis-dev
    - libogg-dev
    - g++-6
    - gcc-6

script:
  # Link gcc-6 and g++-6 to their standard commands
  - sudo ln -sf /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -sf /usr/bin/g++-6 /usr/local/bin/g++
  # Check versions of gcc, g++ and cmake
  - gcc -v
  - g++ -v
  # Run through the make commands
  - ./configure
  - make
  - make test

notifications:
  email: false
