sudo: required
language: cpp
dist: trusty
compiler: g++

before_install:
  - sudo apt-get -qq update

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - cmake
    - time
    - libjpeg-dev
    - libpng12-dev
    - libfreetype6-dev
    - libmikmod-dev
    - libvorbis-dev
    - libogg-dev
    - g++-6

notifications:
  email: false
