sudo: required
language: cpp
dist: trusty
compiler: g++

before_install:
  - sudo apt-get -qq update

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - cmake
    - time
    - g++-5
    - gcc-5
    - binutils
    - libc6

script:
  # Link gcc-6 and g++-6 to their standard commands
  - sudo ln -sf /usr/bin/gcc-5 /usr/local/bin/gcc
  - sudo ln -sf /usr/bin/g++-5 /usr/local/bin/g++
  # Check versions of gcc and g++
  - gcc --version
  - g++ --version
  # Run through the make commands
  - ./configure
  - make
  - make test

cache:
    apt: true
    directories:
    - vendor

notifications:
  email: false
