sudo: required
language: cpp
dist: trusty
compiler: g++

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install g++-7 binutils-2.26
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - export PATH=/usr/lib/binutils-2.26/bin:${PATH}

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - cmake
    - time
    - g++-7
    - gcc-7
    - binutils
    - libc6
    - libc6-amd64
    - libc6-dev
    - libc6-dbg

script:
  # Link gcc-6 and g++-6 to their standard commands
  #- sudo ln -sf /usr/bin/gcc-7 /usr/local/bin/gcc
  #- sudo ln -sf /usr/bin/g++-7 /usr/local/bin/g++
  # Check versions of gcc and g++
  - gcc --version
  - g++ --version
  # Run through the make commands
  - ./configure
  - make
  - make test

cache:
    apt: true
    directories:
    - vendor

notifications:
  email: false
